# Generated by Django 2.0.6 on 2018-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='t1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='t2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tableattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tableattendance',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tableattendance',
            name='ts',
            field=models.TimeField(),
        ),
    ]
