# Generated by Django 2.0.6 on 2018-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0003_auto_20180627_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='t1',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='t2',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='tableattendance',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='tableattendance',
            name='ts',
            field=models.TimeField(default=None),
        ),
    ]
