# Generated by Django 2.0.6 on 2018-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0005_auto_20180627_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Present_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='Total_number',
            field=models.IntegerField(default=0),
        ),
    ]
