# Generated by Django 2.0.6 on 2018-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0006_auto_20180702_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Fraud_number',
            field=models.IntegerField(default=0),
        ),
    ]
