# Generated by Django 2.0.6 on 2018-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0007_person_fraud_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
