# Generated by Django 2.0.6 on 2018-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0008_person_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.URLField(max_length=500)),
                ('group_id', models.CharField(default='22', max_length=100)),
            ],
        ),
    ]
