# Generated by Django 2.0.6 on 2018-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0009_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(max_length=500),
        ),
    ]
