# Generated by Django 2.0.7 on 2018-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camapp', '0012_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableattendance',
            name='time1',
            field=models.TimeField(null=True),
        ),
    ]
